---
title: "Mini-Reflect"
---

Question 1

The first mini project looks at the standard error and expected value of different distributions like the uniform, normal, and beta distributions for example. The project connects to the concept of sampling distributions by showing how the max and min values behave across samples with different probability distributions. This project shows us how choosing the correct distribution to use influences the variability in all the different statistics we would create from the sample. In the larger scheme of things, this mini-project showed you can apply sampling distributions to more than the sample mean, which is what most people use sampling for. Mini-project 2 connects to the concept of estimations. If we are doing hypothesis tests or confidence intervals, we will most likely be looking at data from samples. Throughout the course we were looking at bias and variance and in this mini-project I explained the idea of bias, that the tree I sampled the number of troops from may be biased.

Mini-project 3 is looking at simulating thousands of sample proportions p from a binomial distribution, creating CIs, and then measuring the coverage rate and average width. The project connects with the class for example n=5 and p=0.1, the coverage rate is only 40%, so the true proportion p is contained only in 40% of the intervals. This connects to the class as it shows that even if we simulate thousands of times, a small sample leads to inaccurate and unreliable confidence intervals. The project shows that simply applying formulas and running thousands of simulations does not overcome the limitations of a small sample. This is a big idea of the whole class, the idea of central limit thereon and normally distributed.

Mini-project 4 connects to the content of the course by outlining another method for inference. This project highlights in terms of Bayesian inference, that without strong prior knowledge, inference should more lean on the observed data. This project illustrates how a prior can skew a distribution disproportionally. This connects to the content of the course by explaining that sometimes having too small of a credible interval is always the best as they misrepresent the uncertainty that we actually have.

Mini-project 5 connects to the class by looking into whether the p-value should be the be-all and end-all of making decisions in terms of hypothesis tests. If we use a significance level of 0.05 and the p-value comes out at 0.1, we simply say, we do not have enough evidence to reject Ho and that is the end of whether something affects another. What we learned in class is p-value is the indicator of the final word but mini-project 5 shows we should look at more things like context, where the data comes from, how its cleaned and used, and asses what effect this research will have.

Question 2

Mini-project 3 and mini-project 4 connect in that they both explain how confidence intervals and credible intervals can misrepresent information and people can come to the wrong conclusions due to that fact. In the Bayesian mini-project we saw that we had an extremely tight credible interval which is often good but in this case, the prior was too strong which made the CI too overly confident of Nadal's performance against Novak. Mini-project 3 with n=5 and p=0.1, a confidence interval will be created and someone who doesn't know much about statistics may use that confidence interval to make decisions. Once again, the true proportion is only captured 40% of the time, so it would not be wise to use this CI. The connection between these two is a misrepresentation of results and the negative effects of that.

Mini-projects 2 and 5 related to the coursework by using the modern approach to teaching math stat. By writing a story with definitions and terms, you are having to not just do the math but understand it which is what the course is trying to achieve. In my mini-project 2, I explained the missile strike rate using a binomial distribution, and this is related to the coursework goal of being able to explain ideas from the class, not just do the math. In Mini-project 5, we had to explain our thoughts on the topic of p values. The two mini-projects relate in that a math stat course should prepare you for more than just doing math, but should prepare you to explain concepts or debate against ideas, using a math stat background.

Mini-project 2 and mini-project 4 both look at the idea of statistical inference from a frequentist and Bayesian point of view. In my Vietnam story, we calculated enemy number based on the number of troops behind two trees to find out how many there were in total. Mini project 4 uses a Bayesian approach and we use a prior and create a posterior after we have observed data. The Vietnam project estimates with observed data alone whereas the Nadal project uses prior information and observed data. Both projects look at how we incorporate uncertainty when estimating. After we have looked at where the p-value comes from and used p values a lot, mini-project 5 serves as warning to, us future possible statisticians.

Question 3

My biggest takeaway is that statistical tools have their faults and you really have to look at the methods of research way more clearly to know if you can trust the research and whether you should make decisions based on someone else research. Two examples are a researcher could use a Bayesian approach and make their prior so strong as to make their research prove a point or a researcher could create confidence intervals from too small of a sample which misrepresents a conclusion. Researchers could also manipulate it to reach a certain p-value. The takeaway is that, when looking at research take more time to read the methods and less time reading the conclusion, if you want to know if it is worth making decisions from.

I personally really enjoyed the mini-projects as it gave me some time to do repeated processes and see what was happening. When we would have to change small things of code, many times in different places, it really helped me understand the code and then the concepts as I am someone who needs to repeat tasks to fully understand it.
